Dog command + GET Util
0mlml/Ilmarinen pull request #19
Opened 2024-08-03 13:01 UTC by RAdu2005

Added Dog command that gets media from API and uploads to Discord
From my research, you can't upload a file to Discord without downloading/streaming locally in JDA
Added Gson to dependencies to parse response
Added a GET request Util

Removed unnecessary logger from Help command

Might want to investigate GIF media never showing up. There is no error, there just never happens to receive a .gif in API response (in my testing).

2024-08-03 13:02 UTC, 0mlml commented
Hmmm, I accessed it in my browser a couple times and saw a .gif pop up. That's where I got that from.

2024-08-03 13:07 UTC, 0mlml requested changes
If a JSON library is already imported, we should probably redo the config in JSON

2024-08-03 13:07 UTC, 0mlml commented on build.gradle
> +    implementation 'com.google.code.gson:gson:2.11.0'
A whole dependency for this is awful, but I guess .JSON was mandatory at some point for interacting with APIs. Does JDA already have a JSON library so we don't have two?

2024-08-03 13:07 UTC, 0mlml commented on src/main/java/dev/mlml/command/impl/Dog.java
> +            String fileName = mediaURl.substring(mediaURl.lastIndexOf('/') + 1);
Isn't there a function to parse this?

2024-08-03 13:07 UTC, 0mlml commented on src/main/java/dev/mlml/command/impl/Dog.java
> +                byte[] buffer = new byte[1024];
1024 bytes maximum cannot be correct...

2024-08-03 13:15 UTC, RAdu2005 commented on src/main/java/dev/mlml/command/impl/Dog.java
> +                byte[] buffer = new byte[1024];
ChatGPT and it works decent even on videos

2024-08-03 13:16 UTC, RAdu2005 commented on build.gradle
> +    implementation 'com.google.code.gson:gson:2.11.0'
I'm not sure, their documentation is a bit hard to navigate.

2024-08-03 13:17 UTC, RAdu2005 commented on src/main/java/dev/mlml/command/impl/Dog.java
> +            String fileName = mediaURl.substring(mediaURl.lastIndexOf('/') + 1);
where?

2024-08-03 14:18 UTC, 0mlml commented on build.gradle
> +    implementation 'com.google.code.gson:gson:2.11.0'
I was thinking you could just check their dependencies list

2024-08-03 14:19 UTC, 0mlml commented on src/main/java/dev/mlml/command/impl/Dog.java
> +            String fileName = mediaURl.substring(mediaURl.lastIndexOf('/') + 1);
"ChatGPT, how do I parse a filename from a URL?" 
and see if it has a better solution

2024-08-03 14:19 UTC, 0mlml commented on src/main/java/dev/mlml/command/impl/Dog.java
> +                byte[] buffer = new byte[1024];
Okay

2024-08-03 19:43 UTC, RAdu2005 commented
Increased buffer to 4096.
Found a JDA Json library and used that instead
used .getFile() for name of file

2024-08-03 20:08 UTC, 0mlml requested changes

2024-08-03 20:08 UTC, 0mlml commented on src/main/java/dev/mlml/Utils.java
> +    public static DataObject sendGetRequest(String urlString) {
For completeness sake, a post request should be implemented at this point, I'll make a ticket for it as it's out of scope for this PR

2024-08-03 20:08 UTC, 0mlml commented on src/main/java/dev/mlml/command/impl/Dog.java
> +        logger.info("Media URL is: " + mediaURl);
This should be a debug print

2024-08-05 20:30 UTC, 0mlml approved these changes

2024-08-05 20:30 UTC, merged